resource_group         = "rg-todo-dev-001"
location               = "eastus"
sqlServerName          = "sql-todo-dev"
sqlServerAdminName     = "admin"
sqlServerAdminPassword = "4-v3ry-53cr37-p455w0rd"
sqlDatabaseName        = "sqldb-todo-dev"